apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
 
namespace: staging
 
namePrefix: staging-
 
commonLabels:
  environment: staging
  team: platform
 
resources:
  - ../../apps/webapp
 
configMapGenerator:
  - name: webapp-config
    behavior: merge
    literals:
    - ENVIRONMENT=staging
    - VERSION=1.0.0-rc
    - LOG_LEVEL=info
    - FEATURE_FLAG_NEW_UI=true
 
replicas:
  - name: webapp
    count: 2
 
images:
  - name: nginxdemos/hello
    newTag: latest
