apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
 
namespace: prod
 
namePrefix: prod-
 
commonLabels:
  environment: production
  team: platform
 
resources:
  - ../../apps/webapp
 
configMapGenerator:
  - name: webapp-config
    behavior: merge
    literals:
    - ENVIRONMENT=production
    - VERSION=1.0.0
    - LOG_LEVEL=warn
    - FEATURE_FLAG_NEW_UI=true
 
replicas:
  - name: webapp
    count: 3
 
images:
  - name: nginxdemos/hello
    newTag: latest
