apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
  app: webapp
  managed-by: github-actions
spec:
  replicas: 2
  selector:
  matchLabels:
    app: webapp
  template:
  metadata:
    labels:
    app: webapp
  spec:
    containers:
    - name: webapp
    image: nginxdemos/hello:latest
    ports:
    - containerPort: 80
      name: http
    env:
    - name: ENVIRONMENT
      valueFrom:
      configMapKeyRef:
        name: webapp-config
        key: ENVIRONMENT
    - name: VERSION
      valueFrom:
      configMapKeyRef:
        name: webapp-config
        key: VERSION
    resources:
      requests:
      memory: "64Mi"
      cpu: "50m"
    livenessProbe:
      httpGet:
      path: /
      port: http
      initialDelaySeconds: 10
      periodSeconds: 10
    readinessProbe:
      httpGet:
      path: /
      port: http
      initialDelaySeconds: 5
      periodSeconds: 5
