apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
 
resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
 
commonLabels:
  app: webapp
  version: v1.0.0
 
namespace: default
